apiVersion: v1
kind: Pod
metadata:
    name: pod-hostpath
    namespace: audit-zone
spec:
    containers:
        - name: nginx
          image: nginx
          securityContext:
              runAsNonRoot: true
          volumeMounts:
              - name: host-root
                mountPath: /host
    volumes:
        - name: host-root
          hostPath:
              path: /
