apiVersion: v1
kind: Pod
metadata:
    name: pod-root-user
    namespace: audit-zone
spec:
    containers:
        - name: nginx
          image: nginx
          securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 0
              runAsNonRoot: false
