apiVersion: v1
kind: Namespace
metadata:
    name: clients
    labels:
        name: clients
---
apiVersion: v1
kind: Namespace
metadata:
    name: tenant
    labels:
        name: tenant
---
apiVersion: v1
kind: Namespace
metadata:
    name: accountant
    labels:
        name: accountant
---
apiVersion: v1
kind: Namespace
metadata:
    name: data
    labels:
        name: data
