apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredRunAsNonRootUser
metadata:
    name: disable-root-user
spec:
    match:
        kinds:
            - apiGroups: [""]
              kinds: ["Pod"]
            - apiGroups: ["apps"]
              kinds: ["Deployment", "StatefulSet", "DaemonSet"]
        namespaces:
            - audit-zone
