apiVersion: v1
kind: ConfigMap
metadata:
    name: config-secure-2-index
    namespace: audit-zone
data:
    index.html: |
        <!DOCTYPE html>
        <html>
            <body>
                hello
            </body>
        </html>
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-secure-2
    namespace: audit-zone
spec:
    containers:
        - name: nginx
          image: nginx
          securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                  drop:
                      - ALL
              seccompProfile:
                  type: RuntimeDefault
          volumeMounts:
              - name: index-volume
                mountPath: /usr/share/nginx/html
                readOnly: true
    volumes:
        - name: index-volume
          configMap:
              name: config-secure-2-index
