apiVersion: v1
kind: Pod
metadata:
    name: pod-secure-3
    namespace: audit-zone
spec:
    containers:
        - name: nginx
          image: nginx
          securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                  drop:
                      - ALL
              seccompProfile:
                  type: RuntimeDefault
